Repository NordicSemiconductor/pc-nrfconnect-npm, pull requests merged in 2024-02, with the labels that each got.

#131 pmicControl: Update callback regexs
  src/features/pmicControl/npm/npm1300/buck/buckCallbacks.ts
  src/features/pmicControl/npm/npm1300/buck/buckEffects.ts
  src/features/pmicControl/npm/npm1300/ldo/ldoCallbacks.ts
  src/features/pmicControl/npm/npm1300/pof/pofCallbacks.ts
  src/features/pmicControl/npm/npm1300/tests/commandCallbacks.test.ts
  src/features/pmicControl/npm/npm1300/tests/onlineSetters.test.ts
  src/features/pmicControl/npm/npm1300/tests/requestUpdates.test.ts
Labels: doc not required

#132 Remove soft start value workaround and add soft start to overlay
  src/components/Cards/LDO/LDOCard.tsx
  src/features/pmicControl/npm/npm1300/ldo/ldoCallbacks.ts
  src/features/pmicControl/npm/npm1300/tests/exportImport.test.ts
  src/features/pmicControl/npm/npm1300/tests/offlineSetters.test.ts
  src/features/pmicControl/npm/overlay/overlay.ts
  src/features/pmicControl/npm/types.ts
  src/features/pmicControl/npm/useNpmDevice.tsx
Labels: doc not required

#133 Feat: update FW
  fw/app_signed_1.0.1+1074416698.hex
  fw/app_signed_1.0.1+381901201.hex
  src/features/pmicControl/npm/npm1300/pmic1300Device.tsx
Labels: doc not required

#130 pmicControl: npm1300: Added PWM and PFM buck modes
  src/features/pmicControl/npm/npm1300/buck/buckCallbacks.ts
  src/features/pmicControl/npm/npm1300/buck/buckEffects.ts
  src/features/pmicControl/npm/npm1300/tests/commandCallbacks.test.ts
  src/features/pmicControl/npm/npm1300/tests/onlineSetters.test.ts
  src/features/pmicControl/npm/npm1300/tests/requestUpdates.test.ts
  src/features/pmicControl/npm/overlay/overlay.ts
  src/features/pmicControl/npm/types.ts
Labels: doc required, Do Not Merge

#134 ci: use shared workflow
  .github/workflows/labels.yml
Labels: doc not required, ui not required

#136 Feat: Remove changelog title
  Changelog.md
Labels: doc not required, ui not required

#135 Feat: update dependancies
  package-lock.json
  package.json
  src/actions/fileActions.ts
  src/components/SidePanel/OpenSerialTerminal.tsx
  src/features/pmicControl/npm/deviceSetups.tsx
  src/index.tsx
Labels: doc not required, ui not required

#138 Feat/add support for battery slots
  src/appReducer.ts
  src/components/FuelGauge/FuelGaugeSettings.tsx
  src/components/FuelGauge/SlotSelectionDownloadDialog.tsx
  src/components/Profiling/Dialog/ConfigurationDialog.tsx
  src/components/Profiling/ProfilingProjects/ProfileComponentMenu.tsx
  src/components/Profiling/ProfilingProjects/ProjectCardMenu.tsx
  src/components/Profiling/helpers.ts
  src/features/pmicControl/downloadBatteryModelSlice.ts
  src/features/pmicControl/npm/basePmicDevice.ts
  src/features/pmicControl/npm/npm1300/fuelGauge/fuelGaugeCallbacks.ts
  src/features/pmicControl/npm/npm1300/fuelGauge/profileDownload.ts
  src/features/pmicControl/npm/npm1300/pmic1300Device.tsx
  src/features/pmicControl/npm/npm1300/tests/commandCallbacks.test.ts
  src/features/pmicControl/npm/npm1300/tests/requestUpdates.test.ts
  src/features/pmicControl/npm/pmicHelpers.ts
  src/features/pmicControl/npm/types.ts
  src/features/pmicControl/npm/useNpmDevice.tsx
  src/features/pmicControl/pmicControlSlice.ts
  src/index.tsx
Labels: doc not required, ui not required

#137 Feat/embed battery models
  .eslintrc.js
  resources/batteryModels/npm1300/LiPol/LP302535 (200 mAh).inc
  resources/batteryModels/npm1300/LiPol/LP302535 (200 mAh).json
  resources/batteryModels/npm1300/LiPol/LP353035 (300 mAh).inc
  resources/batteryModels/npm1300/LiPol/LP353035 (300 mAh).json
  resources/batteryModels/npm1300/LiPol/LP502540 (500 mAh).inc
  resources/batteryModels/npm1300/LiPol/LP502540 (500 mAh).json
  resources/batteryModels/npm1300/LiPol/LP503030 (400 mAh).inc
  resources/batteryModels/npm1300/LiPol/LP503030 (400 mAh).json
  resources/batteryModels/npm1300/LiPol/LP602760 (1000 mAh).inc
  resources/batteryModels/npm1300/LiPol/LP602760 (1000 mAh).json
  resources/batteryModels/npm1300/LiPol/LP603035 (600 mAh).inc
  resources/batteryModels/npm1300/LiPol/LP603035 (600 mAh).json
  resources/batteryModels/npm1300/LiPol/LP803035 (800 mAh).inc
  resources/batteryModels/npm1300/LiPol/LP803035 (800 mAh).json
  resources/batteryModels/npm1300/LiPol/LP803448 (1350 mAh).inc
  resources/batteryModels/npm1300/LiPol/LP803448 (1350 mAh).json
  resources/batteryModels/npm1300/Renata/ICP403029PL02 (325 mAh).inc
  resources/batteryModels/npm1300/Renata/ICP403029PL02 (325 mAh).json
  resources/batteryModels/npm1300/Renata/ICP582035PR01 (340 mAh).inc
  resources/batteryModels/npm1300/Renata/ICP582035PR01 (340 mAh).json
  resources/batteryModels/npm1300/Renata/ICP582930PR (450 mAh).inc
  resources/batteryModels/npm1300/Renata/ICP582930PR (450 mAh).json
  resources/batteryModels/npm1300/Renata/ICP621333PA01 (240 mAh).inc
  resources/batteryModels/npm1300/Renata/ICP621333PA01 (240 mAh).json
  resources/batteryModels/npm1300/Renata/ICP622540PMT (600 mAh).inc
  resources/batteryModels/npm1300/Renata/ICP622540PMT (600 mAh).json
  resources/batteryModels/npm1300/Renata/ICP632136HPST (520 mAh).inc
  resources/batteryModels/npm1300/Renata/ICP632136HPST (520 mAh).json
  resources/batteryModels/npm1300/Renata/ICP641620PA01 (165 mAh).inc
  resources/batteryModels/npm1300/Renata/ICP641620PA01 (165 mAh).json
  resources/batteryModels/npm1300/Renata/ICP682828HPMT (560 mAh).inc
  resources/batteryModels/npm1300/Renata/ICP682828HPMT (560 mAh).json
  src/actions/fileActions.ts
  src/components/FuelGauge/FuelGaugeSettings.tsx
  src/components/FuelGauge/SlotSelectionDownloadDialog.tsx
  src/components/Profiling/ProfilingProjects/ProfileComponent.tsx
  src/components/Profiling/ProfilingProjects/ProfileComponentMenu.tsx
  src/components/Profiling/ProfilingProjects/Profiles.tsx
  src/components/Profiling/ProfilingProjects/ProjectCardMenu.tsx
  src/components/Profiling/ProfilingProjects/profilingProjects.scss
  src/features/helpers.ts
  src/features/pmicControl/downloadBatteryModelSlice.ts
Labels: doc not required, ui not required

#139 Feat: update tooltips
  src/components/FuelGauge/FuelGaugeSettings.tsx
  src/features/pmicControl/npm/npm1300/documentationPmic1300.tsx
Labels: doc required, ui not required
