Repository NordicSemiconductor/pc-nrfconnect-npm, pull requests merged in 2025-03, with the labels that each got.

#196 fix: add missing values to 2100 apply config
  src/features/pmicControl/npm/npm2100/gpio/gpioSetters.tsx
  src/features/pmicControl/npm/npm2100/ldo/index.ts
  src/features/pmicControl/npm/npm2100/tests/exportImport.test.ts
Labels: doc not required, ui not required

#197 refactor: make initialize an optional method
  src/features/pmicControl/npm/basePmicDevice.ts
  src/features/pmicControl/npm/useNpmDevice.tsx
Labels: doc not required, ui not required

#198 fix: use LOW ship mode current when entering break to wake mode
  src/features/pmicControl/npm/npm2100/lowPower/lowPowerActions.ts
Labels: doc not required, ui not required

#193 fix: only use one softstart instead of having it split with loadswitc…
  src/components/Cards/LDO/LDOCard.tsx
  src/features/pmicControl/npm/npm1300/ldo/index.ts
  src/features/pmicControl/npm/npm1300/ldo/ldoCallbacks.ts
  src/features/pmicControl/npm/npm1300/ldo/ldoSet.tsx
  src/features/pmicControl/npm/npm1300/ldo/types.ts
  src/features/pmicControl/npm/npm1300/tests/commandCallbacks.test.ts
  src/features/pmicControl/npm/npm1300/tests/onlineSetters.test.ts
  src/features/pmicControl/npm/npm2100/ldo/index.ts
  src/features/pmicControl/npm/npm2100/ldo/ldoCallbacks.ts
  src/features/pmicControl/npm/npm2100/ldo/ldoGet.ts
  src/features/pmicControl/npm/npm2100/ldo/ldoSet.ts
  src/features/pmicControl/npm/npm2100/tests/ldo/commandCallbackLdo.test.ts
  src/features/pmicControl/npm/npm2100/types.ts
  src/features/pmicControl/npm/types.ts
Labels: doc not required, ui not required

#199 docs: add missing tooltips
  src/components/SystemFeatures/VBus.tsx
  src/features/pmicControl/npm/npm1300/documentationPmic1300.tsx
Labels: doc not required, ui not required

#200 feat: update nrfutil
  package.json
Labels: doc not required, ui not required

#202 fix: don't show onoffcontrol if no onoffcontrol...
  src/components/Cards/LDO/LDOCard.tsx
Labels: doc not required, ui not required

#204 fix: fix yet another ??
  src/components/Cards/LDO/LDOCard.tsx
Labels: doc not required, ui not required

#201 docs: add break-to-wake tooltip
  src/features/pmicControl/npm/npm2100/documentationPmic2100.tsx
Labels: doc required, ui not required

#195 doc: update overview for Tau release
  doc/docs/evaluating_battery.md
  doc/docs/overview.md
  doc/docs/profiling_battery.md
  doc/docs/screenshots/npm_overview_app.png
  doc/docs/screenshots/npm_overview_npm1300.png
  doc/docs/screenshots/npm_select_device_virtual.png
  doc/docs/screenshots/npm_select_device_virtual_menu.png
Labels: documentation, doc required

#205 doc: review all tooltips and align them
  src/components/SystemFeatures/ResetControl.tsx
  src/features/pmicControl/npm/npm1300/documentationPmic1300.tsx
  src/features/pmicControl/npm/npm1300/tests/offlineSetters.test.ts
  src/features/pmicControl/npm/npm2100/documentationPmic2100.tsx
  src/features/pmicControl/npm/types.ts
Labels: documentation

#192 Battery profiling: improve battery name validation
  Changelog.md
  package-lock.json
  package.json
  src/components/Profiling/Dialog/ConfigurationDialog.tsx
Labels: doc required, ui required

#194 docs: up version and add changelog
  Changelog.md
  package.json
Labels: doc required, ui not required

#206 docs: add missing break to wake tooltip
  src/components/SystemFeatures/LowPower.tsx
Labels: doc not required, ui not required

#207 Fix: documentation typo
  src/features/pmicControl/npm/npm2100/documentationPmic2100.tsx
Labels: doc not required, ui not required

#208 Fix package lock
  package-lock.json
Labels: doc not required, ui not required

#210 remove npm_chg_status_check from npm2100
  src/features/pmicControl/npm/npm1300/tests/onlineSetters.test.ts
  src/features/pmicControl/npm/npm2100/fuelGauge/fuelGaugeSet.tsx
  src/features/pmicControl/npm/npm2100/tests/onlineSetters.test.ts
  src/features/pmicControl/npm/types.ts
  src/features/pmicControl/npm/useNpmDevice.tsx
Labels: doc not required, ui not required

#209 Add: support for disable_positive_deltaz
  fw/app_signed_nPM2100_0.7.0+0.hex
  fw/app_signed_nPM2100_0.7.1+0.hex
  src/components/Battery/Battery.tsx
  src/components/Cards/Battery/BatteryCard.tsx
  src/features/pmicControl/npm/basePmicDevice.ts
  src/features/pmicControl/npm/npm1300/fuelGauge/fuelGaugeCallbacks.ts
  src/features/pmicControl/npm/npm1300/fuelGauge/fuelGaugeSet.ts
  src/features/pmicControl/npm/npm1300/tests/commandCallbacks.test.ts
  src/features/pmicControl/npm/npm1300/tests/exportImport.test.ts
  src/features/pmicControl/npm/npm1300/tests/offlineSetters.test.ts
  src/features/pmicControl/npm/npm2100/documentationPmic2100.tsx
  src/features/pmicControl/npm/npm2100/fuelGauge/fuelGaugeCallbacks.ts
  src/features/pmicControl/npm/npm2100/fuelGauge/fuelGaugeGet.tsx
  src/features/pmicControl/npm/npm2100/fuelGauge/fuelGaugeSet.tsx
  src/features/pmicControl/npm/npm2100/pmic2100Device.tsx
  src/features/pmicControl/npm/npm2100/tests/commandCallbacks.test.ts
  src/features/pmicControl/npm/npm2100/tests/offlineSetters.test.ts
  src/features/pmicControl/npm/npm2100/tests/onlineSetters.test.ts
  src/features/pmicControl/npm/types.ts
  src/features/pmicControl/npm/useNpmDevice.tsx
  src/features/pmicControl/pmicControlSlice.ts
  src/index.scss
Labels: doc required, ui not required

#211 Release 2.0.0 prepare
  Changelog.md
  package-lock.json
  package.json
Labels: doc not required, ui not required

#212 doc: remove LCS mention
  doc/docs/index.md
Labels: documentation
